USE PRT681_Groundwater;

-- 1. AVERAGE WATER QUALITY BY BORE STATUS
SELECT
    B.STATUS,
    COUNT(WQ.BORE_NO) AS Samples,
    AVG(WQ.PH_LAB) AS AveragePH,
    AVG(WQ.EC_LAB) AS AverageEC,
    AVG(WQ.TDS) AS AverageTDS,
    AVG(WQ.HARD) AS AverageHardness
FROM Bores B
INNER JOIN Water_Quality WQ
    ON B.BORE_NO = WQ.BORE_NO
GROUP BY B.STATUS
ORDER BY B.STATUS;


-- 2. AVERAGE WATER QUALITY BY BORE PURPOSE
SELECT
    B.PURPOSE,
    COUNT(WQ.BORE_NO) AS Samples,
    AVG(WQ.PH_LAB) AS AveragePH,
    AVG(WQ.EC_LAB) AS AverageEC,
    AVG(WQ.TDS) AS AverageTDS
FROM Bores B
INNER JOIN Water_Quality WQ
    ON B.BORE_NO = WQ.BORE_NO
GROUP BY B.PURPOSE
ORDER BY AverageTDS DESC;


-- 3. RISK CLASS VS WATER QUALITY
SELECT
    B.RISK_CLASS,
    COUNT(WQ.BORE_NO) AS Samples,
    AVG(WQ.PH_LAB) AS AveragePH,
    AVG(WQ.EC_LAB) AS AverageEC,
    AVG(WQ.TDS) AS AverageTDS,
    AVG(WQ.HARD) AS AverageHardness
FROM Bores B
INNER JOIN Water_Quality WQ
    ON B.BORE_NO = WQ.BORE_NO
GROUP BY B.RISK_CLASS
ORDER BY B.RISK_CLASS;


-- 4. TOP BORES BY AVERAGE TDS
SELECT TOP 15
    B.BORE_NO,
    B.BORE_NAME,
    B.STATUS,
    B.PURPOSE,
    B.RISK_CLASS,
    B.YIELD,
    AVG(WQ.TDS) AS AverageTDS,
    AVG(WQ.EC_LAB) AS AverageEC,
    COUNT(WQ.BORE_NO) AS SampleCount
FROM Bores B
INNER JOIN Water_Quality WQ
    ON B.BORE_NO = WQ.BORE_NO
WHERE WQ.TDS IS NOT NULL
GROUP BY
    B.BORE_NO,
    B.BORE_NAME,
    B.STATUS,
    B.PURPOSE,
    B.RISK_CLASS,
    B.YIELD
HAVING COUNT(WQ.BORE_NO) >= 3
ORDER BY AverageTDS DESC;


-- 5. TOP BORES BY AVERAGE YIELD WITH WATER QUALITY
SELECT TOP 15
    B.BORE_NO,
    B.BORE_NAME,
    B.STATUS,
    B.PURPOSE,
    B.RISK_CLASS,
    B.YIELD,
    AVG(WQ.TDS) AS AverageTDS,
    AVG(WQ.EC_LAB) AS AverageEC,
    AVG(WQ.PH_LAB) AS AveragePH,
    COUNT(WQ.BORE_NO) AS SampleCount
FROM Bores B
INNER JOIN Water_Quality WQ
    ON B.BORE_NO = WQ.BORE_NO
WHERE B.YIELD IS NOT NULL
GROUP BY
    B.BORE_NO,
    B.BORE_NAME,
    B.STATUS,
    B.PURPOSE,
    B.RISK_CLASS,
    B.YIELD
ORDER BY B.YIELD DESC;


-- 6. CURRENT MONITORING STATIONS WITH BORE INFORMATION
SELECT
    COUNT(*) AS CurrentMonitoringStations,
    AVG(B.YIELD) AS AverageYield,
    AVG(B.RISK_CLASS) AS AverageRiskClass
FROM Groundwater_Level G
INNER JOIN Bores B
    ON G.UFI = B.UFI
WHERE G.ACTIVE = 'Current';


-- 7. MONITORING STATIONS BY BORE STATUS
SELECT
    B.STATUS,
    G.ACTIVE,
    COUNT(*) AS StationCount
FROM Groundwater_Level G
INNER JOIN Bores B
    ON G.UFI = B.UFI
GROUP BY B.STATUS, G.ACTIVE
ORDER BY B.STATUS, G.ACTIVE;