USE PRT681_Groundwater;

-- 1. AVERAGE YIELD BY BORE PURPOSE
SELECT
    PURPOSE,
    COUNT(*) AS BoreCount,
    AVG(YIELD) AS AverageYield,
    MAX(YIELD) AS MaximumYield
FROM Bores
WHERE YIELD IS NOT NULL
GROUP BY PURPOSE
ORDER BY AverageYield DESC;


-- 2. AVERAGE YIELD BY RISK CLASS
SELECT
    RISK_CLASS,
    COUNT(*) AS BoreCount,
    AVG(YIELD) AS AverageYield,
    MAX(YIELD) AS MaximumYield
FROM Bores
WHERE YIELD IS NOT NULL
GROUP BY RISK_CLASS
ORDER BY RISK_CLASS;


-- 3. CURRENT VS HISTORICAL YIELD
SELECT
    STATUS,
    COUNT(*) AS BoreCount,
    AVG(YIELD) AS AverageYield,
    MAX(YIELD) AS MaximumYield
FROM Bores
WHERE YIELD IS NOT NULL
GROUP BY STATUS
ORDER BY AverageYield DESC;


-- 4. WATER QUALITY COVERAGE BY BORE STATUS
SELECT
    B.STATUS,
    COUNT(DISTINCT B.UFI) AS BoreCount,
    COUNT(WQ.BORE_NO) AS WaterQualitySamples
FROM Bores B
LEFT JOIN Water_Quality WQ
    ON B.BORE_NO = WQ.BORE_NO
GROUP BY B.STATUS
ORDER BY B.STATUS;


-- 5. BORES WITH HIGH YIELD AND HIGH TDS
SELECT TOP 20
    B.UFI,
    B.BORE_NO,
    B.BORE_NAME,
    B.YIELD,
    B.STATUS,
    B.PURPOSE,
    WQ.SAMPLEDATE,
    WQ.TDS,
    WQ.EC_LAB,
    WQ.PH_LAB
FROM Bores B
INNER JOIN Water_Quality WQ
    ON B.BORE_NO = WQ.BORE_NO
WHERE B.YIELD IS NOT NULL
  AND WQ.TDS IS NOT NULL
ORDER BY B.YIELD DESC, WQ.TDS DESC;


-- 6. GROUNDWATER MONITORING STATIONS JOINED TO BORE INFORMATION
SELECT TOP 20
    G.UFI,
    G.STATION,
    G.STATION_NA,
    G.ACTIVE,
    B.BORE_NO,
    B.BORE_NAME,
    B.STATUS,
    B.PURPOSE,
    B.RISK_CLASS,
    B.YIELD
FROM Groundwater_Level G
INNER JOIN Bores B
    ON G.UFI = B.UFI
ORDER BY G.UFI;